namespace SpriteKind {
    export const Cursor = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 1 1 1 1 1 1 1 . . . . . 
        . . . 1 1 1 1 1 1 1 1 1 . . . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 . . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 . . . 
        . . . 1 1 1 1 1 1 1 1 1 . . . . 
        . . . . 1 1 1 1 1 1 1 . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Camera, Render.getAttribute(Render.attribute.dirX) * 110, Render.getAttribute(Render.attribute.dirY) * 110)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jump(Render.getRenderSpriteInstance(), 90, -250)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.gameOver(true)
})
controller.menu.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.toggleViewMode()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let projectile: Sprite = null
let Camera: Sprite = null
game.stats = true
tiles.setCurrentTilemap(tilemap`level5`)
Render.setViewMode(ViewMode.raycastingView)
Camera = Render.getRenderSpriteInstance()
Camera.setPosition(132, 92)
Render.setZOffset(Camera, 8)
Render.SetAttribute(Render.attribute.wallZScale, 2)
let MyShark = sprites.create(img`
    ....................ccfff...........
    ..........fffffffffcbbbbf...........
    .........fbbbbbbbbbfffbf............
    .........fbb111bffbbbbff............
    .........fb11111ffbbbbbcff..........
    .........f1cccc11bbcbcbcccf.........
    ..........fc1c1c1bbbcbcbcccf...ccccc
    ............c3331bbbcbcbccccfccddbbc
    ...........c333c1bbbbbbbcccccbddbcc.
    ...........c331c11bbbbbcccccccbbcc..
    ..........cc13c111bbbbccccccffbccf..
    ..........c111111cbbbcccccbbc.fccf..
    ...........cc1111cbbbfdddddc..fbbcf.
    .............cccffbdbbfdddc....fbbf.
    ..................fbdbbfcc......fbbf
    ...................fffff.........fff
    `, SpriteKind.Enemy)
MyShark.setPosition(75, 50)
Render.setZOffset(MyShark, 4)
MyShark.setVelocity(1, 1)
MyShark.setScale(0.5, ScaleAnchor.Middle)
MyShark.setBounceOnWall(true)
Render.setSpriteAnimations(MyShark, Render.createAnimations(2000, [img`
    .............ccfff..................
    ...........ccddbcf..................
    ..........ccddbbf...................
    ..........fccbbcf...................
    .....fffffccccccff.........ccc......
    ...ffbbbbbbbcbbbbcfff....ccbbc......
    ..fbbbbbbbbcbcbbbbcccff.cdbbc.......
    ffbbbbbbffbbcbcbbbcccccfcdbbf.......
    fbcbbb11ff1bcbbbbbcccccffbbf........
    fbbb11111111bbbbbcccccccbbcf........
    .fb11133cc11bbbbcccccccccccf........
    ..fccc31c111bbbcccccbdbffbbcf.......
    ...fc13c111cbbbfcddddcc..fbbf.......
    ....fccc111fbdbbccdcc.....fbbf......
    ........ccccfcdbbcc........fff......
    .............fffff..................
    `,img`
    .............ccfff..................
    ............cddbbf..................
    ...........cddbbf...................
    ..........fccbbcf............ccc....
    ....ffffffccccccff.........ccbbc....
    ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
    ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
    fbcbbbbbffbbcbcbbbcccccfffdbbf......
    fbbb1111ff1bcbcbbbcccccccbbbcf......
    .fb11111111bbbbbbcccccccccbccf......
    ..fccc33cc11bbbbccccccccfffbbcf.....
    ...fc131c111bbbcccccbdbc...fbbf.....
    ....f33c111cbbbfdddddcc.....fbbf....
    .....ff1111fbdbbfddcc........fff....
    .......cccccfbdbbfc.................
    .............fffff..................
    `,img`
    .............ccfff..................
    ............cddbbf..................
    ...........cddbbf...................
    ..........fccbbcf............ccc....
    ....ffffffccccccff.........ccbbc....
    ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
    ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
    fbcbbbbbffbbcbcbbbcccccfffdbbf......
    fbbb1111ff1bcbcbbbcccccccbbbcf......
    .fb11111111bbbbbbcccccccccbccf......
    ..fccc33cc11bbbbccccccccfffbbcf.....
    ...fc131c111bbbcccccbdbc...fbbf.....
    ....f33c111cbbbfdddddcc.....fbbf....
    .....ff1111fbdbbfddcc........fff....
    .......cccccfbdbbfc.................
    .............fffff..................
    `,img`
    ..................ccfff.............
    .................cddbbf.............
    ........fffffffffddbbf..............
    .......fbbbbbbbbbfcbcf..............
    .......fbbc111bffbbccffff...........
    .......fb111111ffbbbbbcccff....ccccc
    ........f1cc3311bbcbcbbccccf..cdbbbc
    ........fcc131c1bbbcbcbcccccfcddbbc.
    .........f111111bbbcbcbccccccbdbbf..
    .........f1111111bbbbbccccccccbbcf..
    ..........f111111bbbbcccccccffbccf..
    ...........c1111cbbbcccccbdbc.fbbcf.
    ............cc11cbbbfddddddc...fbbf.
    ..............cffbdbbfdddcc.....fbbf
    .................fbdbbfcc........fff
    ..................fffff.............
    `], [img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    .............fffcc..................
    .............fbbddc.................
    ..............fbbddfffffffff........
    ..............fcbcfbbbbbbbbbf.......
    ...........ffffccbbffb111cbbf.......
    ccccc....ffcccbbbbbff111111bf.......
    cbbbdc..fccccbbcbcbb1133cc1f........
    .cbbddcfcccccbcbcbbb1c131ccf........
    ..fbbdbccccccbcbcbbb111111f.........
    ..fcbbccccccccbbbbb1111111f.........
    ..fccbffcccccccbbbb111111f..........
    .fcbbf.cbdbcccccbbbc1111c...........
    .fbbf...cddddddfbbbc11cc............
    fbbf.....ccdddfbbdbffc..............
    fff........ccfbbdbf.................
    .............fffff..................
    `]))
let Myshark2 = sprites.create(img`
    ....................ccfff...........
    ..........fffffffffcbbbbf...........
    .........fbbbbbbbbbfffbf............
    .........fbb111bffbbbbff............
    .........fb11111ffbbbbbcff..........
    .........f1cccc11bbcbcbcccf.........
    ..........fc1c1c1bbbcbcbcccf...ccccc
    ............c3331bbbcbcbccccfccddbbc
    ...........c333c1bbbbbbbcccccbddbcc.
    ...........c331c11bbbbbcccccccbbcc..
    ..........cc13c111bbbbccccccffbccf..
    ..........c111111cbbbcccccbbc.fccf..
    ...........cc1111cbbbfdddddc..fbbcf.
    .............cccffbdbbfdddc....fbbf.
    ..................fbdbbfcc......fbbf
    ...................fffff.........fff
    `, SpriteKind.Enemy)
Myshark2.setPosition(60, 5)
Render.setZOffset(Myshark2, 4)
Myshark2.setVelocity(1, 1)
Myshark2.setScale(0.5, ScaleAnchor.Middle)
Myshark2.setBounceOnWall(true)
Render.setSpriteAnimations(Myshark2, Render.createAnimations(2000, [img`
    .............ccfff..................
    ...........ccddbcf..................
    ..........ccddbbf...................
    ..........fccbbcf...................
    .....fffffccccccff.........ccc......
    ...ffbbbbbbbcbbbbcfff....ccbbc......
    ..fbbbbbbbbcbcbbbbcccff.cdbbc.......
    ffbbbbbbffbbcbcbbbcccccfcdbbf.......
    fbcbbb11ff1bcbbbbbcccccffbbf........
    fbbb11111111bbbbbcccccccbbcf........
    .fb11133cc11bbbbcccccccccccf........
    ..fccc31c111bbbcccccbdbffbbcf.......
    ...fc13c111cbbbfcddddcc..fbbf.......
    ....fccc111fbdbbccdcc.....fbbf......
    ........ccccfcdbbcc........fff......
    .............fffff..................
    `,img`
    .............ccfff..................
    ............cddbbf..................
    ...........cddbbf...................
    ..........fccbbcf............ccc....
    ....ffffffccccccff.........ccbbc....
    ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
    ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
    fbcbbbbbffbbcbcbbbcccccfffdbbf......
    fbbb1111ff1bcbcbbbcccccccbbbcf......
    .fb11111111bbbbbbcccccccccbccf......
    ..fccc33cc11bbbbccccccccfffbbcf.....
    ...fc131c111bbbcccccbdbc...fbbf.....
    ....f33c111cbbbfdddddcc.....fbbf....
    .....ff1111fbdbbfddcc........fff....
    .......cccccfbdbbfc.................
    .............fffff..................
    `,img`
    .............ccfff..................
    ............cddbbf..................
    ...........cddbbf...................
    ..........fccbbcf............ccc....
    ....ffffffccccccff.........ccbbc....
    ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
    ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
    fbcbbbbbffbbcbcbbbcccccfffdbbf......
    fbbb1111ff1bcbcbbbcccccccbbbcf......
    .fb11111111bbbbbbcccccccccbccf......
    ..fccc33cc11bbbbccccccccfffbbcf.....
    ...fc131c111bbbcccccbdbc...fbbf.....
    ....f33c111cbbbfdddddcc.....fbbf....
    .....ff1111fbdbbfddcc........fff....
    .......cccccfbdbbfc.................
    .............fffff..................
    `,img`
    ..................ccfff.............
    .................cddbbf.............
    ........fffffffffddbbf..............
    .......fbbbbbbbbbfcbcf..............
    .......fbbc111bffbbccffff...........
    .......fb111111ffbbbbbcccff....ccccc
    ........f1cc3311bbcbcbbccccf..cdbbbc
    ........fcc131c1bbbcbcbcccccfcddbbc.
    .........f111111bbbcbcbccccccbdbbf..
    .........f1111111bbbbbccccccccbbcf..
    ..........f111111bbbbcccccccffbccf..
    ...........c1111cbbbcccccbdbc.fbbcf.
    ............cc11cbbbfddddddc...fbbf.
    ..............cffbdbbfdddcc.....fbbf
    .................fbdbbfcc........fff
    ..................fffff.............
    `], [img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `,img`
    .............fffcc..................
    .............fbbddc.................
    ..............fbbddfffffffff........
    ..............fcbcfbbbbbbbbbf.......
    ...........ffffccbbffb111cbbf.......
    ccccc....ffcccbbbbbff111111bf.......
    cbbbdc..fccccbbcbcbb1133cc1f........
    .cbbddcfcccccbcbcbbb1c131ccf........
    ..fbbdbccccccbcbcbbb111111f.........
    ..fcbbccccccccbbbbb1111111f.........
    ..fccbffcccccccbbbb111111f..........
    .fcbbf.cbdbcccccbbbc1111c...........
    .fbbf...cddddddfbbbc11cc............
    fbbf.....ccdddfbbdbffc..............
    fff........ccfbbdbf.................
    .............fffff..................
    `]))
MyShark.follow(Camera, 30)
Myshark2.follow(Camera, 30)
forever(function () {
    if (browserEvents.MouseLeft.isPressed() == true) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . 1 1 1 1 1 1 1 . . . . . 
            . . . 1 1 1 1 1 1 1 1 1 . . . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 . . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 . . . 
            . . . 1 1 1 1 1 1 1 1 1 . . . . 
            . . . . 1 1 1 1 1 1 1 . . . . . 
            . . . . . . . . . . . . . . . . 
            `, Camera, Render.getAttribute(Render.attribute.dirX) * 110, Render.getAttribute(Render.attribute.dirY) * 110)
    }
})
